In [73]:
import pandas as pd
import numpy as np

In [75]:
xl = pd.ExcelFile('./NVT_Metadatentabelle_MASTER.xlsm')

In [76]:
xl.sheet_names  # see all sheet names

['Produktionen',
 'Ereignisse',
 'Objekte VIDEOS',
 'Objekte TEXT',
 'Objekte BILD',
 'Objekte AUDIO',
 '||_Personen',
 '||_Gruppen_Ensembles',
 '||_Veranstaltungsort',
 '||_Städte',
 '||_Länder',
 'Sammlungen',
 'Serie',
 'TYPEN und GLOSSARE',
 'Fragen und Dok',
 'TODOs',
 'Legende',
 'Unterobjekt Beispiele',
 'Übersicht']

In [77]:
## events = pd.read_excel('./NVT_Metadatentabelle_MASTER.xlsm', sheet_name='Ereignisse')

In [136]:
productions = pd.read_excel('./NVT_Metadatentabelle_MASTER.xlsm', sheet_name='Produktionen', header=1)

In [146]:
prclean = (productions[productions['Identifier / geeinigter Name'].str.contains('PR', na=False)] ## drops all rows that don't start with 'PR' or are NaN
           .drop(['Musik (für GEMA)'], axis='columns') ## drops unmodeled column
           .drop([2]) ## drops example row
           .reset_index(drop=True) ## resets index to be continouus
           .rename(columns={'Identifier / geeinigter Name':'ID', ## renames columns for future reference
                                          'Produktionsname / Titel':'PR_Titel',
                                          'Quelle (Beschreibung)':'Q_Beschreibung',
                                          'Verwendete Texte':'Verwendete_Texte',
                                          'Autor(en) der Texte':'Autoren_Texte',
                                          'Beteiligte Gruppen / Compagnies':'Beteiligte_Gruppen',
                                          'Sprecher*in':'SprecherIn',
                                          'Darsteller allgem.':'Darsteller',
                                          'Weitere Mitwirkende':'Mitwirkende',
                                          'Spielzeit / Laufzeit Start':'Spielzeit_Start',
                                          'Spielzeit / Laufzeit Ende':'Spielzeit_Ende'
}))

In [147]:
prclean.head()

,ID,PR_Titel,Beschreibung,Q_Beschreibung,Verwendete_Texte,Autoren_Texte,Produktionstyp,Beteiligte_Gruppen,Konzept,Textbearbeitung,...,Musiker,Komposition,Mitwirkende,Premierendatum,Dernierendatum,Spielzeit_Start,Spielzeit_Ende,Veranstaltungsort,Stadt,Land
0,PR_12_Traeume_des_Dr_Fridkin,12 Träume des Dr. Fridkin,"Produktion des Mime-Theater ""Version"" aus Tsch...",TN; Programmheft Woche des Gestischen Theaters...,NaN,NaN,NaN,G_Version,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tscheljabinsk,UDSSR
1,PR_Amapola,Amapola,NaN,NaN,NaN,"Omar_Saavedra,Santis",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PR_Ameriques,Ameriques,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PR_Aufstand_der_Traeume,Aufstand der Träume,Mimodrama,NaN,Aufstand der Träume,"Andreas,Ittner",NaN,G_Pantomime_Ensemble_Jena,NaN,NaN,...,NaN,NaN,"Michel,Willebrand;Christoffer,Petschow;Falko,S...",NaN,NaN,NaN,NaN,NaN,Jena,DDR
4,PR_August_August,"August, August",NaN,NaN,NaN,NaN,NaN,NaN,"Peter,Baumgart",NaN,...,NaN,"Dietrich,Petzold",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN